"use client";
import { useState } from 'react';
import { Button } from '../../components/ui/button';
import { ConfirmDialog } from '../../components/ui/confirm-dialog';
import type { Schema } from '../../lib/api/client';
import { useConversation } from './use-conversation';
import { ConversationHistory } from './conversation-history';
export function MealWorkspace({ conversationId }: { conversationId?: string }) {
  const chat = useConversation(conversationId);
  const [category, setCategory] = useState('Both');
  const categories: Schema['Category'][] = category === 'Both' ? ['restaurant','recipe'] : category === 'Cook' ? ['recipe'] : ['restaurant'];
  return <main id="main" className="workspace"><h1>What sounds good?</h1><p className="note">Synthetic teaching catalog</p><p>Choose a place to eat or something to cook. Explore the sources behind each suggestion.</p><div className="actions"><Button variant="secondary" disabled={chat.busy} onClick={chat.startNew}>New conversation</Button>{chat.id && <ConfirmDialog trigger="Delete conversation" title="Delete this conversation?" busy={chat.busy} onConfirm={chat.deleteConversation}>This removes its history, preferences and unshared uploads. A new conversation keeps this one available at its URL.</ConfirmDialog>}</div><fieldset className="category-choice" disabled={chat.busy || chat.loading}><legend>Find a meal</legend>{['Eat out','Cook','Both'].map((label) => <label key={label}><input name="category" type="radio" checked={category === label} onChange={() => setCategory(label)} />{label}</label>)}</fieldset><div className="actions">{['Find Italian restaurants in San Francisco','Help me choose a recipe with chickpeas'].map((example) => <Button variant="secondary" key={example} disabled={chat.busy} onClick={() => chat.setDraft(example)}>{example}</Button>)}</div>{chat.loading && <p role="status">Loading saved conversation…</p>}{chat.error && <p className="notice error" role="alert">{chat.error}</p>}<ConversationHistory history={chat.history} events={chat.events} /><form className="composer stack" onSubmit={(e) => { e.preventDefault(); void chat.send(categories); }}><label htmlFor="message">Message</label><textarea id="message" rows={3} maxLength={2000} value={chat.draft} disabled={chat.busy || chat.loading} onChange={(e) => chat.setDraft(e.target.value)} placeholder="Tell us what you feel like eating…" /><p className="note">Follow up here to refine the same conversation.</p><div className="actions"><Button type="submit" disabled={chat.busy || chat.loading || !chat.draft.trim()}>Send</Button>{chat.busy && <Button type="button" variant="secondary" onClick={chat.stop}>Stop</Button>}</div></form></main>;
}
