"use client";
import { useState } from 'react';
import { Button } from '../../components/ui/button';
import { ConfirmDialog } from '../../components/ui/confirm-dialog';
import type { Schema } from '../../lib/api/client';
import { PreferencesPanel } from '../preferences/preferences-panel';
import { useConversation } from './use-conversation';
import { ImageAttachment } from './image-attachment';
import { ConversationHistory } from './conversation-history';
export function MealWorkspace({ conversationId }: { conversationId?: string }) {
  const chat = useConversation(conversationId);
  const [attachment, setAttachment] = useState<{ id?: string; blocked: boolean }>({ blocked: false });
  const [attachmentKey, setAttachmentKey] = useState(0);
  const [pending, setPending] = useState<Schema['PreferenceUpdate']>();
  const [category, setCategory] = useState('Both');
  const categories: Schema['Category'][] = category === 'Both' ? ['restaurant','recipe'] : category === 'Cook' ? ['recipe'] : ['restaurant'];
  return <main id="main" className="workspace"><h1>What sounds good?</h1><p className="note">Synthetic teaching catalog</p><p>Choose a place to eat or something to cook. Explore the sources behind each suggestion.</p><div className="actions"><Button variant="secondary" disabled={chat.busy} onClick={() => { chat.startNew(); setPending(undefined); setAttachment({ blocked: false }); setAttachmentKey((key) => key + 1); }}>New conversation</Button>{chat.id && <ConfirmDialog trigger="Delete conversation" title="Delete this conversation?" busy={chat.busy} onConfirm={chat.deleteConversation}>This removes its history, preferences and unshared uploads. A new conversation keeps this one available at its URL.</ConfirmDialog>}</div><fieldset className="category-choice" disabled={chat.busy || chat.loading}><legend>Find a meal</legend>{['Eat out','Cook','Both'].map((label) => <label key={label}><input name="category" type="radio" checked={category === label} onChange={() => setCategory(label)} />{label}</label>)}</fieldset><div className="actions">{['Find Italian restaurants in San Francisco','Help me choose a recipe with chickpeas'].map((example) => <Button variant="secondary" key={example} disabled={chat.busy} onClick={() => chat.setDraft(example)}>{example}</Button>)}</div>{chat.loading && <p role="status">Loading saved conversation…</p>}{chat.error && <p className="notice error" role="alert">{chat.error}</p>}<div className="meal-layout"><PreferencesPanel key={JSON.stringify(chat.history?.preferences)} saved={chat.history?.preferences} pending={pending} onChange={setPending} disabled={chat.busy || chat.loading} /><div className="meal-main"><ConversationHistory history={chat.history} events={chat.events} /><form className="composer stack" onSubmit={(e) => { e.preventDefault(); if (attachment.blocked) return; void chat.send(categories, pending, attachment.id).then((accepted) => { if (accepted) { setPending(undefined); setAttachment({ blocked: false }); setAttachmentKey((key) => key + 1); } }); }}><label htmlFor="message">Message</label><textarea id="message" rows={3} maxLength={2000} value={chat.draft} disabled={chat.busy || chat.loading} onChange={(e) => chat.setDraft(e.target.value)} placeholder="Tell us what you feel like eating…" /><ImageAttachment key={attachmentKey} disabled={chat.busy || chat.loading} onChange={(id, blocked) => setAttachment({ id, blocked })} /><p className="note">Follow up here to refine the same conversation.</p><div className="actions"><Button type="submit" disabled={chat.busy || chat.loading || attachment.blocked || !chat.draft.trim()}>Send</Button>{chat.busy && <Button type="button" variant="secondary" onClick={chat.stop}>Stop</Button>}</div></form></div></div></main>;
}
